# Generated by Django 5.1.6 on 2025-02-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Active', 'Active')], max_length=20)),
                ('loan_type', models.CharField(choices=[('EMI', 'EMI'), ('Interest Only', 'Interest Only')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_type', models.CharField(choices=[('Principal', 'Principal'), ('Interest', 'Interest')], max_length=20)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.loaninfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('kyc_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_loan_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.loanstatus')),
                ('loan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.loaninfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanListed',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('requester_type', models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium')], max_length=20)),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='API.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to='API.userinfo'),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='lender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_loans', to='API.userinfo'),
        ),
    ]
