# Generated by Django 5.1.6 on 2025-02-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninfo',
            name='borrower_id',
        ),
        migrations.RemoveField(
            model_name='loanlisted',
            name='requester_id',
        ),
    ]
