# Generated by Django 5.1.6 on 2025-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_loaninfo_borrower_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='tenure',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
