# Generated by Django 5.1.6 on 2025-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_loaninfo_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='completed_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
