# Generated by Django 5.1.6 on 2025-02-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_loaninfo_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninfo',
            name='completed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
