# Generated by Django 5.1.6 on 2025-02-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_loaninfo_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='applied_loan_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.loanlisted'),
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
    ]
