# Generated by Django 5.1.6 on 2025-02-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_userinfo_applied_loan_status_delete_loanstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFinance',
            fields=[
                ('finance_id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.account'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transportation', 'Transportation'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
                ('type', models.CharField(choices=[('Monthly', 'Monthly'), ('Periodically', 'Periodically'), ('Yearly', 'Yearly')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.personalfinance')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='personal_finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.personalfinance'),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
